#!/bin/sh

convertVideoToAudio() {
    input=$1
    /usr/bin/ffmpeg -i "$input" -ar 16000 -ac 1 -c:a pcm_s16le -y /tmp/output.wav&> /dev/null
    echo "/tmp/output.wav"
}


convertAudioToSubtitle() {
    whispercpp_pid = $(pgrep whispercpp)
    if [ -n "$whispercpp_pid" ]; then
        kill -9 $whispercpp_pid
    fi
    input=$1
    /usr/bin/whispercpp -m /usr/share/whispercpp/model/ggml-tiny.en-q5_0.bin -osrt -f "$input" 
}

handleRequest() {
    action=$1

    if [ "$action" = "list" ]; then
        methods="{\"ffmpeg\":{\"description\":\"Convert video to audio\",\"params\":{\"input\":{\"type\":\"string\",\"description\":\"Input video file\"}}},\"whispercpp\":{\"description\":\"Convert audio to subtitle\",\"params\":{\"input\":{\"type\":\"string\",\"description\":\"Input audio file\"}}}}"
        echo "$methods"
    elif [ "$action" = "call" ]; then
        method=$2

        if [ "$method" = "ffmpeg" ]; then
            input="/tmp/video.mp4"
            output=$(convertVideoToAudio "$input")
            result="{\"result\":\"ok\",\"data\":{\"output\":\"$output\"}}"
            echo "$result"
        elif [ "$method" = "whispercpp" ]; then
            input="/tmp/output.wav"
            convertAudioToSubtitle "$input"
            result="{\"result\":\"ok\",\"data\":{\"output\":\"/tmp/output.srt\"}}"
            echo "$result"
        else
            errorResult="{\"result\":\"error\",\"message\":\"Unknown method\"}"
            echo "$errorResult"
        fi
    fi
}

handleRequest "$@"
